// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YS.CoffeeMachine.Infrastructure;

#nullable disable

namespace YS.CoffeeMachine.Infrastructure.Migrations.timeDbMigrations
{
    [DbContext(typeof(CoffeeMachineTimescaleDBContext))]
    [Migration("20250708073531_v1.2.1")]
    partial class v121
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YS.CoffeeMachine.Domain.AggregatesModel.Basics.Log.DeviceMetricsLog", b =>
                {
                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() AT TIME ZONE 'UTC')");

                    b.Property<int>("CounterNo")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("EnterpriseinfoId")
                        .HasColumnType("bigint");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<int>("MetricType")
                        .HasColumnType("integer");

                    b.Property<string>("Mid")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("DeviceId", "Timestamp");

                    b.HasIndex("DeviceId", "Timestamp")
                        .IsUnique();

                    b.ToTable("devicemetricslog", (string)null);
                });

            modelBuilder.Entity("YS.CoffeeMachine.Domain.AggregatesModel.Basics.Log.DeviceOnlineLog", b =>
                {
                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() AT TIME ZONE 'UTC')");

                    b.Property<string>("DeviceModelName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("EnterpriseinfoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Mid")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("DeviceId", "Timestamp");

                    b.HasIndex("DeviceId", "Timestamp")
                        .IsUnique();

                    b.ToTable("deviceonlinelog", (string)null);
                });

            modelBuilder.Entity("YS.CoffeeMachine.Domain.AggregatesModel.Basics.Log.PlatformOperationLog", b =>
                {
                    b.Property<long>("OperationUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("(now() AT TIME ZONE 'UTC')");

                    b.Property<string>("Describe")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EnterpriseinfoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Ip")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Mid")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OperationUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("Result")
                        .HasColumnType("boolean");

                    b.Property<int>("TrailType")
                        .HasColumnType("integer");

                    b.HasKey("OperationUserId", "Timestamp");

                    b.HasIndex("OperationUserId", "Timestamp")
                        .IsUnique();

                    b.ToTable("PlatformOperationLog", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
